set -U fish_color_autosuggestion 747369
set -U fish_color_cancel \x2d\x2dreverse
set -U fish_color_command 99cc99
set -U fish_color_comment ffcc66
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_end cc99cc
set -U fish_color_error f2777a
set -U fish_color_escape 66cccc
set -U fish_color_history_current \x2d\x2dbold
set -U fish_color_host normal
set -U fish_color_host_remote \x1d
set -U fish_color_keyword \x1d
set -U fish_color_match 6699cc
set -U fish_color_normal normal
set -U fish_color_operator 6699cc
set -U fish_color_option \x1d
set -U fish_color_param d3d0c8
set -U fish_color_quote ffcc66
set -U fish_color_redirection d3d0c8
set -U fish_color_search_match bryellow\x1e\x2d\x2dbackground\x3dbrblack
set -U fish_color_selection white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
set -U fish_color_user brgreen
set -U fish_color_valid_path \x2d\x2dunderline
set -U fish_key_bindings fish_default_key_bindings
set -U fish_pager_color_background \x1d
set -U fish_pager_color_completion normal
set -U fish_pager_color_description B3A06D
set -U fish_pager_color_prefix normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
set -U fish_pager_color_progress brwhite\x1e\x2d\x2dbackground\x3dcyan
set -U fish_pager_color_secondary_background \x1d
set -U fish_pager_color_secondary_completion \x1d
set -U fish_pager_color_secondary_description \x1d
set -U fish_pager_color_secondary_prefix \x1d
set -U fish_pager_color_selected_background \x2d\x2dbackground\x3dbrblack
set -U fish_pager_color_selected_completion \x1d
set -U fish_pager_color_selected_description \x1d
set -U fish_pager_color_selected_prefix \x1d
